-- Generated:
-- ./lua scripts/script.lua --input=scripts/test/2html.lua --output=docs/sampling_2html.lua --sample --instructions=250 --path="scripts/?.lua"
--
-- Format:
-- ./lua scripts/script.lua --input=docs/sampling_2html.lua --format --path="scripts/?.lua"
return {
	header = {
		clockid = "nano",
		instrument = false,
		memory = false,
		sample = true,
		callback = false,
		single_thread = false,
		mismatch = false,
		line_freq = false,
		compress_graph = true,
		sampler_count = 250,
		instr_count = 283250,
		profile_overhead = 2389200,
		calibration = 0,
	},
	records = {
		{
			id = "0",
			func = "0",
			parent = "0",
			parent_line = 0,
			ignored = false,
			name = "(root)",
			what = "C",
			source = "(root)",
			count = 1,
			linedefined = 0,
			lastlinedefined = 0,
			nups = 0,
			nparams = 0,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "17",
			func = "5601a1ddea20",
			parent = "5601a1ddea20",
			parent_line = 0,
			ignored = false,
			name = "getcounter",
			what = "Lua",
			source = "getcounter (scripts/test/2html.lua:177)",
			count = 8,
			linedefined = 177,
			lastlinedefined = 184,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "38",
			func = "5601a1de20f0",
			parent = "5601a1dd3840",
			parent_line = 0,
			ignored = false,
			name = "ff",
			what = "Lua",
			source = "ff (scripts/test/2html.lua:263)",
			count = 2,
			linedefined = 263,
			lastlinedefined = 265,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1",
			func = "5601a0111940",
			parent = "0",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "C",
			source = "? [C]",
			count = 1,
			linedefined = -1,
			lastlinedefined = -1,
			nups = 0,
			nparams = 0,
			isvararg = 1,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "7",
			func = "5601a0152c60",
			parent = "5601a1de5740",
			parent_line = 0,
			ignored = false,
			name = "gsub",
			what = "C",
			source = "gsub [C]",
			count = 1,
			linedefined = -1,
			lastlinedefined = -1,
			nups = 0,
			nparams = 0,
			isvararg = 1,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "28",
			func = "5601a1dd8bd0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:94)",
			count = 6,
			linedefined = 94,
			lastlinedefined = 100,
			nups = 3,
			nparams = 4,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "29",
			func = "5601a1ddc900",
			parent = "5601a1de78c0",
			parent_line = 0,
			ignored = false,
			name = "code",
			what = "Lua",
			source = "code (scripts/test/2html.lua:72)",
			count = 67,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "6",
			func = "5601a1de5740",
			parent = "5601a1dd3960",
			parent_line = 0,
			ignored = false,
			name = "trata",
			what = "Lua",
			source = "trata (scripts/test/2html.lua:439)",
			count = 1,
			linedefined = 439,
			lastlinedefined = 450,
			nups = 4,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "22",
			func = "5601a1dd9820",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:318)",
			count = 6,
			linedefined = 318,
			lastlinedefined = 318,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2d",
			func = "5601a1ddc900",
			parent = "5601a1de6bc0",
			parent_line = 0,
			ignored = false,
			name = "b",
			what = "Lua",
			source = "b (scripts/test/2html.lua:72)",
			count = 5,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1e",
			func = "5601a1de20f0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:263)",
			count = 1,
			linedefined = 263,
			lastlinedefined = 265,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "f",
			func = "5601a1dd3840",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:58)",
			count = 11,
			linedefined = 58,
			lastlinedefined = 58,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2a",
			func = "5601a1dda9a0",
			parent = "5601a1de78c0",
			parent_line = 0,
			ignored = false,
			name = "antipara",
			what = "Lua",
			source = "antipara (scripts/test/2html.lua:130)",
			count = 7,
			linedefined = 130,
			lastlinedefined = 132,
			nups = 0,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "8",
			func = "5601a1de26d0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:440)",
			count = 317,
			linedefined = 440,
			lastlinedefined = 448,
			nups = 4,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "16",
			func = "5601a1dda6c0",
			parent = "5601a1de6bc0",
			parent_line = 0,
			ignored = false,
			name = "fixpara",
			what = "Lua",
			source = "fixpara (scripts/test/2html.lua:124)",
			count = 11,
			linedefined = 124,
			lastlinedefined = 128,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "21",
			func = "5601a1ddc900",
			parent = "5601a1dce230",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:72)",
			count = 2,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "24",
			func = "5601a1ddc900",
			parent = "5601a1ddad00",
			parent_line = 0,
			ignored = false,
			name = "code",
			what = "Lua",
			source = "code (scripts/test/2html.lua:72)",
			count = 7,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "20",
			func = "5601a1ddee30",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:192)",
			count = 2,
			linedefined = 192,
			lastlinedefined = 192,
			nups = 0,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "13",
			func = "5601a1dd8df0",
			parent = "5601a1de1b30",
			parent_line = 0,
			ignored = false,
			name = "nopara",
			what = "Lua",
			source = "nopara (scripts/test/2html.lua:118)",
			count = 2,
			linedefined = 118,
			lastlinedefined = 122,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "12",
			func = "5601a1de1b30",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:255)",
			count = 7,
			linedefined = 255,
			lastlinedefined = 260,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "5",
			func = "5601a1ddc900",
			parent = "5601a1dd3960",
			parent_line = 0,
			ignored = false,
			name = "b",
			what = "Lua",
			source = "b (scripts/test/2html.lua:72)",
			count = 1,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "23",
			func = "5601a1ddad00",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:293)",
			count = 7,
			linedefined = 293,
			lastlinedefined = 297,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1d",
			func = "5601a1ddc900",
			parent = "5601a1dce790",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:72)",
			count = 4,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "35",
			func = "5601a1de7000",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:366)",
			count = 1,
			linedefined = 366,
			lastlinedefined = 370,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "26",
			func = "5601a1de78c0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:383)",
			count = 32,
			linedefined = 383,
			lastlinedefined = 396,
			nups = 4,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3f",
			func = "5601a1ddd440",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:107)",
			count = 19,
			linedefined = 107,
			lastlinedefined = 115,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "a",
			func = "5601a1ddc900",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:72)",
			count = 191,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1a",
			func = "5601a1ddf0e0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:197)",
			count = 17,
			linedefined = 197,
			lastlinedefined = 197,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3c",
			func = "5601a1dd8bd0",
			parent = "5601a1de7ff0",
			parent_line = 0,
			ignored = false,
			name = "anchor",
			what = "Lua",
			source = "anchor (scripts/test/2html.lua:94)",
			count = 8,
			linedefined = 94,
			lastlinedefined = 100,
			nups = 3,
			nparams = 4,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1c",
			func = "5601a1dde700",
			parent = "5601a1dce230",
			parent_line = 0,
			ignored = false,
			name = "inccounter",
			what = "Lua",
			source = "inccounter (scripts/test/2html.lua:170)",
			count = 11,
			linedefined = 170,
			lastlinedefined = 175,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2f",
			func = "5601a1ddd260",
			parent = "5601a1dcdb00",
			parent_line = 0,
			ignored = false,
			name = "makeref",
			what = "Lua",
			source = "makeref (scripts/test/2html.lua:102)",
			count = 2,
			linedefined = 102,
			lastlinedefined = 105,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "9",
			func = "5601a1de5740",
			parent = "5601a1de26d0",
			parent_line = 0,
			ignored = false,
			name = "trata",
			what = "Lua",
			source = "trata (scripts/test/2html.lua:439)",
			count = 131,
			linedefined = 439,
			lastlinedefined = 450,
			nups = 4,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "c",
			func = "5601a1de7190",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:372)",
			count = 3,
			linedefined = 372,
			lastlinedefined = 372,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3d",
			func = "5601a1de25c0",
			parent = "5601a1ddad00",
			parent_line = 0,
			ignored = false,
			name = "lua2link",
			what = "Lua",
			source = "lua2link (scripts/test/2html.lua:268)",
			count = 1,
			linedefined = 268,
			lastlinedefined = 270,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "25",
			func = "5601a1dcdd30",
			parent = "5601a1dce230",
			parent_line = 0,
			ignored = false,
			name = "getparam",
			what = "Lua",
			source = "getparam (scripts/test/2html.lua:211)",
			count = 4,
			linedefined = 211,
			lastlinedefined = 216,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2c",
			func = "5601a1ddc900",
			parent = "5601a1de7b30",
			parent_line = 0,
			ignored = false,
			name = "em",
			what = "Lua",
			source = "em (scripts/test/2html.lua:72)",
			count = 4,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "27",
			func = "5601a1dd3840",
			parent = "5601a1de78c0",
			parent_line = 0,
			ignored = false,
			name = "pre",
			what = "Lua",
			source = "pre (scripts/test/2html.lua:58)",
			count = 7,
			linedefined = 58,
			lastlinedefined = 58,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1b",
			func = "5601a1de8390",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:415)",
			count = 5,
			linedefined = 415,
			lastlinedefined = 419,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "32",
			func = "5601a1dded50",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:189)",
			count = 2,
			linedefined = 189,
			lastlinedefined = 189,
			nups = 1,
			nparams = 0,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2b",
			func = "5601a1de7b30",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:421)",
			count = 24,
			linedefined = 421,
			lastlinedefined = 434,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3e",
			func = "5601a0152c60",
			parent = "5601a1dd3960",
			parent_line = 0,
			ignored = false,
			name = "gsub",
			what = "C",
			source = "gsub [C]",
			count = 1,
			linedefined = -1,
			lastlinedefined = -1,
			nups = 0,
			nparams = 0,
			isvararg = 1,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "19",
			func = "5601a1dd96e0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:314)",
			count = 5,
			linedefined = 314,
			lastlinedefined = 316,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "4",
			func = "5601a1dd3960",
			parent = "7f8f00205a60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "main",
			source = "main chunk (scripts/test/2html.lua)",
			count = 2,
			linedefined = 0,
			lastlinedefined = 0,
			nups = 1,
			nparams = 0,
			isvararg = 1,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "d",
			func = "5601a1dce230",
			parent = "5601a1dce790",
			parent_line = 0,
			ignored = false,
			name = "getparamtitle",
			what = "Lua",
			source = "getparamtitle (scripts/test/2html.lua:224)",
			count = 17,
			linedefined = 224,
			lastlinedefined = 241,
			nups = 6,
			nparams = 3,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "e",
			func = "5601a1ddea20",
			parent = "5601a1dce230",
			parent_line = 0,
			ignored = false,
			name = "getcounter",
			what = "Lua",
			source = "getcounter (scripts/test/2html.lua:177)",
			count = 5,
			linedefined = 177,
			lastlinedefined = 184,
			nups = 2,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2e",
			func = "5601a1dcdb00",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:375)",
			count = 1,
			linedefined = 375,
			lastlinedefined = 377,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "34",
			func = "5601a1dd8bd0",
			parent = "5601a1dce230",
			parent_line = 0,
			ignored = false,
			name = "anchor",
			what = "Lua",
			source = "anchor (scripts/test/2html.lua:94)",
			count = 3,
			linedefined = 94,
			lastlinedefined = 100,
			nups = 3,
			nparams = 4,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "14",
			func = "5601a1dda9a0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:130)",
			count = 4,
			linedefined = 130,
			lastlinedefined = 132,
			nups = 0,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "1f",
			func = "5601a1dd8df0",
			parent = "5601a1dd3840",
			parent_line = 0,
			ignored = false,
			name = "ff",
			what = "Lua",
			source = "ff (scripts/test/2html.lua:118)",
			count = 3,
			linedefined = 118,
			lastlinedefined = 122,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "30",
			func = "5601a1dd8bd0",
			parent = "5601a1de78c0",
			parent_line = 0,
			ignored = false,
			name = "anchor",
			what = "Lua",
			source = "anchor (scripts/test/2html.lua:94)",
			count = 9,
			linedefined = 94,
			lastlinedefined = 100,
			nups = 3,
			nparams = 4,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "2",
			func = "5601a1dcfcb0",
			parent = "5601a0111940",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "main",
			source = "main chunk (scripts/script.lua)",
			count = 1,
			linedefined = 0,
			lastlinedefined = 0,
			nups = 1,
			nparams = 0,
			isvararg = 1,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "11",
			func = "5601a1ddd260",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:102)",
			count = 20,
			linedefined = 102,
			lastlinedefined = 105,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "31",
			func = "5601a1de25c0",
			parent = "5601a1dd96e0",
			parent_line = 0,
			ignored = false,
			name = "lua2link",
			what = "Lua",
			source = "lua2link (scripts/test/2html.lua:268)",
			count = 7,
			linedefined = 268,
			lastlinedefined = 270,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "10",
			func = "5601a1ddc900",
			parent = "5601a1dd3840",
			parent_line = 0,
			ignored = false,
			name = "ff",
			what = "Lua",
			source = "ff (scripts/test/2html.lua:72)",
			count = 32,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3b",
			func = "5601a1de25c0",
			parent = "5601a1de7ff0",
			parent_line = 0,
			ignored = false,
			name = "lua2link",
			what = "Lua",
			source = "lua2link (scripts/test/2html.lua:268)",
			count = 10,
			linedefined = 268,
			lastlinedefined = 270,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "33",
			func = "5601a1dcdf40",
			parent = "5601a1dce230",
			parent_line = 0,
			ignored = false,
			name = "gettitle",
			what = "Lua",
			source = "gettitle (scripts/test/2html.lua:219)",
			count = 1,
			linedefined = 219,
			lastlinedefined = 222,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3",
			func = "7f8f00205a60",
			parent = "5601a1dcfcb0",
			parent_line = 0,
			ignored = false,
			name = "file",
			what = "C",
			source = "file [C]",
			count = 1,
			linedefined = -1,
			lastlinedefined = -1,
			nups = 0,
			nparams = 0,
			isvararg = 1,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "37",
			func = "5601a1dcdd30",
			parent = "5601a1de7000",
			parent_line = 0,
			ignored = false,
			name = "getparam",
			what = "Lua",
			source = "getparam (scripts/test/2html.lua:211)",
			count = 1,
			linedefined = 211,
			lastlinedefined = 216,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "39",
			func = "5601a1de7ff0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:398)",
			count = 16,
			linedefined = 398,
			lastlinedefined = 405,
			nups = 4,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "b",
			func = "5601a1dce790",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:244)",
			count = 9,
			linedefined = 244,
			lastlinedefined = 251,
			nups = 7,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "15",
			func = "5601a1de6bc0",
			parent = "5601a0152c60",
			parent_line = 0,
			ignored = false,
			name = "?",
			what = "Lua",
			source = "? (scripts/test/2html.lua:350)",
			count = 19,
			linedefined = 350,
			lastlinedefined = 357,
			nups = 3,
			nparams = 1,
			isvararg = 0,
			istailcall = 32,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "36",
			func = "5601a1ddd260",
			parent = "5601a1de7000",
			parent_line = 0,
			ignored = false,
			name = "makeref",
			what = "Lua",
			source = "makeref (scripts/test/2html.lua:102)",
			count = 1,
			linedefined = 102,
			lastlinedefined = 105,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "18",
			func = "5601a1ddd260",
			parent = "5601a1de7190",
			parent_line = 0,
			ignored = false,
			name = "makeref",
			what = "Lua",
			source = "makeref (scripts/test/2html.lua:102)",
			count = 5,
			linedefined = 102,
			lastlinedefined = 105,
			nups = 1,
			nparams = 1,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
		{
			id = "3a",
			func = "5601a1ddc900",
			parent = "5601a1de7ff0",
			parent_line = 0,
			ignored = false,
			name = "h3",
			what = "Lua",
			source = "h3 (scripts/test/2html.lua:72)",
			count = 40,
			linedefined = 72,
			lastlinedefined = 82,
			nups = 2,
			nparams = 2,
			isvararg = 0,
			istailcall = 0,
			ftransfer = 0,
			ntransfer = 0,
		},
	}
}
